[build]
  command = "prisma generate && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--include=dev"
  CI = "false"
  SECRETS_SCAN_OMIT_PATHS = "tests/*,scripts/*"

[[plugins]]
  package = "@netlify/plugin-nextjs"
