/**
 * Shanvi Hospitality — Official Tour Packages, Services, Bank & Company Data
 * Sourced directly from content/ package documentation.
 */

export interface PackageItineraryDay {
  day: number;
  title: string;
  description: string;
}

export interface TourPackage {
  id: string;
  title: string;
  slug: string;
  type: 'domestic' | 'international';
  destination: string;
  duration: string;
  daysCount: number;
  priceFrom?: string;
  category: string[];
  highlights: string[];
  description: string;
  itinerary?: PackageItineraryDay[];
  inclusions?: string[];
  exclusions?: string[];
  isCustom?: boolean;
}

export interface CompanyService {
  id: string;
  name: string;
  shortDescription: string;
  longDescription: string;
  subServices: string[];
  icon: string;
}

export const SHANVI_BANK_DETAILS = {
  beneficiaryName: "SHANVI HOSPITALITY",
  accountType: "Current Account",
  bankName: "HDFC Bank Ltd.",
  accountNumber: "50200084920194",
  ifscCode: "HDFC0000288",
  branch: "Sector 18, Noida, Uttar Pradesh 201301",
  upiId: "shanvihospitality@hdfcbank",
  qrNote: "Official B2B / B2C remittance account for tour package deposits and invoices.",
};

export const SHANVI_OFFICE_LOCATION = {
  address: "Sector 18, Noida, Gautam Buddha Nagar, Uttar Pradesh 201301, India",
  landmark: "Near Wave Silver Tower & Sector 18 Metro Station (Blue Line)",
  latitude: 28.5708,
  longitude: 77.3271,
  googleMapsUrl: "https://maps.google.com/?q=Sector+18+Noida+Uttar+Pradesh+201301",
  metroConnectivity: "Noida Sector 18 Metro Station (Gate No. 2) — 2 mins walking distance",
  airportDistance: "Indira Gandhi International Airport (IGI) — 32 km via DND Flyway",
  railwayDistance: "New Delhi Railway Station (NDLS) — 18 km / Hazrat Nizamuddin — 14 km",
};

export const SHANVI_COMPANY_INFO = {
  name: "Shanvi Hospitality",
  tagline: "Best Tour Packages In India",
  type: "Travel Agency & Destination Management Company (DMC)",
  legalStatus: "Partnership Firm",
  established: "2022",
  gstNumber: "09AEKFS1932F1ZX",
  gstRegistrationDate: "27-04-2022",
  annualTurnover: "40L - 1.5 Cr",
  website: "https://shanvihospitality.in",
  primaryPhone: "+91 9999885087",
  secondaryPhone: "+91 9355141058",
  whatsapp: "+91 9999885087",
  email: "enquiry@shanvihospitality.in",
  address: {
    area: "Sector 18",
    city: "Noida",
    district: "Gautam Buddha Nagar",
    state: "Uttar Pradesh",
    country: "India",
    fullAddress: "Sector 18, Noida, Gautam Buddha Nagar, Uttar Pradesh 201301, India",
  },
  presence: [
    "Delhi / NCR",
    "Uttarakhand",
    "Madhya Pradesh",
    "Gujarat",
    "Rajasthan",
    "Himachal Pradesh",
    "Kerala",
    "Nepal",
    "Thailand",
    "Vietnam",
  ],
  keyContact: "Himani Ma'am (Tour Planner)",
  businessHours: {
    weekdays: "9:00 AM – 7:00 PM",
    saturday: "10:00 AM – 5:00 PM",
    sunday: "On Call / WhatsApp (24/7 Helpline)",
  },
};

export const SHANVI_SERVICES: CompanyService[] = [
  {
    id: "srv_001",
    name: "Customized Tour Packages",
    shortDescription: "Tailor-made domestic and international holidays designed around traveler budget and style.",
    longDescription: "Whether solo backpackers, honeymooners, or family groups, we craft packages matching exact preferences across Uttarakhand, Rajasthan, Thailand, Vietnam, and beyond.",
    subServices: ["Domestic Tour Packages", "International Tour Packages", "Honeymoon Packages", "Family Tours", "Group Tours", "Corporate MICE"],
    icon: "🗺️",
  },
  {
    id: "srv_002",
    name: "Hotel & Resort Bookings",
    shortDescription: "Direct negotiated rates at handpicked hotels and luxury resorts across India & abroad.",
    longDescription: "Direct DMC tie-ups with premium properties ensuring best contractual rates, complimentary upgrades, and verified hygienic stays.",
    subServices: ["Budget Hotels", "3-Star & 4-Star Hotels", "5-Star Luxury Resorts", "Heritage Havelis", "Wildlife Safari Lodges"],
    icon: "🏨",
  },
  {
    id: "srv_003",
    name: "Transportation & Fleet",
    shortDescription: "Private air-conditioned fleet with experienced tourist drivers and all-India permits.",
    longDescription: "Sedans, Innova Crystas, and luxury Tempo Travellers for airport transfers, intercity journeys, and hill-terrain drives.",
    subServices: ["Airport / Railway Transfers", "Intercity Cab Rentals", "Sightseeing Day Tours", "Luxury Tempo Travellers", "Hill Station Driving Specialists"],
    icon: "🚗",
  },
  {
    id: "srv_004",
    name: "Corporate & MICE Travel",
    shortDescription: "Meetings, Incentives, Conferences, and Exhibitions managed end-to-end.",
    longDescription: "Full logistics, conference venue booking, gala dinners, audio-visual equipment, and team-building offsites.",
    subServices: ["Corporate Offsites", "Dealer Meets & Conferences", "Team Building Retreats", "Incentive Travel Programs"],
    icon: "💼",
  },
  {
    id: "srv_005",
    name: "Adventure & Wildlife Safaris",
    shortDescription: "Jim Corbett tiger safaris, Rishikesh white-water rafting, and Himalayan trekking.",
    longDescription: "Authorized open-gypsy safaris inside Jim Corbett National Park, certified grade III/IV river rafting, and camping.",
    subServices: ["Jim Corbett Jeep Safaris", "Rishikesh White Water Rafting", "Camping & Bonfires", "High-altitude Treks"],
    icon: "🐅",
  },
  {
    id: "srv_006",
    name: "Pilgrimage & Spiritual Tours",
    shortDescription: "Chardham Yatra, Haridwar Ganga Aarti, Mukteshwar Dham, and sacred shrine circuits.",
    longDescription: "Spiritual journeys with senior-citizen priority assistance, VIP Darshan guidance, and comfortable halts.",
    subServices: ["Chardham Yatra", "Do Dham & Ek Dham Yatras", "Haridwar & Rishikesh Aarti", "Mukteshwar Mahadev", "Nepal Pashupatinath"],
    icon: "🕉️",
  },
  {
    id: "srv_007",
    name: "Destination Management (DMC)",
    shortDescription: "B2B local ground handling for travel agents and tour operators across Uttarakhand, Delhi NCR & Nepal.",
    longDescription: "White-label DMC ground operations, hotel allotments, reliable transport fleet, and 24/7 on-ground guest care.",
    subServices: ["B2B Ground Handling", "Hotel Contracting", "Fleet Dispatch", "Local On-ground Guides"],
    icon: "🤝",
  },
  {
    id: "srv_008",
    name: "Serviced Apartments",
    shortDescription: "Fully furnished executive service apartments for extended business or family stays.",
    longDescription: "Centrally located, self-catering apartments in Noida, Delhi NCR, and major hubs offering hotel comforts with home privacy.",
    subServices: ["Short-term Stays", "Monthly Corporate Leases", "Family Suites"],
    icon: "🏢",
  },
];

export const SHANVI_PACKAGES: TourPackage[] = [
  {
    id: "pkg_001",
    title: "Haridwar Corbett Nainital Tour Package",
    slug: "haridwar-corbett-nainital-6d5n",
    type: "domestic",
    destination: "Uttarakhand",
    duration: "6 Days / 5 Nights",
    daysCount: 6,
    priceFrom: "₹18,500 / person",
    category: ["Wildlife", "Pilgrimage", "Hill Station"],
    highlights: [
      "Sacred Ganga Aarti at Har Ki Pauri, Haridwar",
      "Jim Corbett National Park jungle tiger safaris",
      "Naini Peak & Naini Lake boating in Nainital",
      "Hanumangarhi Temple, Bhimtal, Naukuchiatal, Sattal",
      "Mall Road stroll & shopping in Nainital",
      "Private AC cab with driver for all transfers",
    ],
    description: "The classic North India experience uniting sacred Haridwar, thrilling Corbett wildlife, and serene Nainital lakes in 6 picturesque days.",
    itinerary: [
      { day: 1, title: "Delhi Arrival → Haridwar (220 km)", description: "Transfer to Haridwar, hotel check-in, visit Mansa Devi & Chandi Devi temples, evening divine Ganga Aarti at Har Ki Pauri." },
      { day: 2, title: "Haridwar → Jim Corbett (200 km)", description: "Drive to Corbett through scenic foothills, check into resort, evening nature walk and river edge relaxation." },
      { day: 3, title: "Corbett Jeep Safari & Wildlife Exploration", description: "Early morning jeep safari with wildlife naturalist inside Corbett Tiger Reserve, afternoon Garjia Temple visit." },
      { day: 4, title: "Corbett → Nainital Hill Station (70 km)", description: "Scenic uphill drive to Nainital, check into hotel, leisurely evening walk and boat ride along sparkling Naini Lake." },
      { day: 5, title: "Nainital Lake Tour & Viewpoints", description: "Full day sightseeing: Bhimtal, Naukuchiatal, Sattal lakes, Snow View Point, and local Tibetan market shopping." },
      { day: 6, title: "Nainital → Delhi Departure (300 km)", description: "Breakfast, check-out, comfortable drive back to Delhi airport or railway station for return journey." },
    ],
    inclusions: [
      "Accommodation in 3-star/4-star standard rooms on double sharing",
      "Breakfast and dinner included at all hotels",
      "Dedicated private AC vehicle with commercial tourist permit",
      "Toll taxes, parking, interstate permits, and driver allowances",
      "Corbett safari entry coordination",
    ],
    exclusions: [
      "Airfare / Train tickets",
      "Monument and camera entry fees",
      "Personal laundry, phone calls, mineral water, and extra meals",
    ],
  },
  {
    id: "pkg_002",
    title: "Chardham Yatra Sacred Pilgrimage",
    slug: "chardham-yatra-tour-package",
    type: "domestic",
    destination: "Uttarakhand",
    duration: "10-12 Days",
    daysCount: 11,
    priceFrom: "₹38,000 / person",
    category: ["Pilgrimage", "Spiritual", "Himalayan"],
    highlights: [
      "Yamunotri — sacred hot springs and Divya Shila",
      "Gangotri — Bhagirathi origin at high Himalayan altitude",
      "Kedarnath — holy Jyotirlinga shrine amidst snow peaks",
      "Badrinath — sacred Neelkanth peak backdrop",
      "Helicopter / pony coordination assistance",
    ],
    description: "A deeply revered, spiritually transformative pilgrimage to Uttarakhand's four sacred shrines with meticulous vehicle and stay arrangements.",
    itinerary: [
      { day: 1, title: "Haridwar / Rishikesh Arrival → Barkot", description: "Depart for Barkot via Mussoorie and Kempty Falls. Overnight stay in Barkot." },
      { day: 2, title: "Barkot → Yamunotri Darshan → Barkot", description: "Early morning trek to Yamunotri temple, holy bath in Surya Kund, return to Barkot." },
      { day: 3, title: "Barkot → Uttarkashi", description: "Drive along Bhagirathi river to Uttarkashi, visit Kashi Vishwanath temple." },
      { day: 4, title: "Uttarkashi → Gangotri → Uttarkashi", description: "Drive to holy Gangotri temple, witness Submerged Shivling, return to Uttarkashi." },
      { day: 5, title: "Uttarkashi → Guptkashi / Sitapur", description: "Scenic transit through Mandakini valley to Kedarnath base area." },
      { day: 6, title: "Sitapur → Kedarnath Darshan", description: "Trek or helicopter to Kedarnath, evening darshan and Aarti at Lord Shiva shrine." },
      { day: 7, title: "Kedarnath → Sitapur Base", description: "Morning darshan, trek down to Sitapur base, rest and recovery." },
      { day: 8, title: "Sitapur → Badrinath via Chopta", description: "Drive through Chopta valley to holy Badrinath Dham, evening temple Aarti." },
      { day: 9, title: "Badrinath → Mana Village → Rudraprayag", description: "Morning bath in Tapt Kund, visit Mana (India's first village), drive to Rudraprayag." },
      { day: 10, title: "Rudraprayag → Rishikesh / Haridwar Departure", description: "Devprayag confluence darshan, return to Haridwar for onward journey." },
    ],
    inclusions: [
      "Comfortable verified hotel stays across pilgrimage halts",
      "Vegetarian breakfast and dinner daily",
      "Pushback tempo traveller or private vehicle with experienced hill driver",
      "Biometric registration and Yatra permit assistance",
    ],
    exclusions: ["Helicopter tickets, pony/doli charges, VIP Darshan slips"],
  },
  {
    id: "pkg_003",
    title: "Mussoorie Nainital Hill Station Tour",
    slug: "mussoorie-nainital-5d4n",
    type: "domestic",
    destination: "Uttarakhand",
    duration: "5 Days / 4 Nights",
    daysCount: 5,
    priceFrom: "₹15,200 / person",
    category: ["Hill Station", "Leisure", "Honeymoon"],
    highlights: [
      "Kempty Falls & Lal Tibba highest peak in Mussoorie",
      "Gun Hill ropeway ride with Doon valley view",
      "Naini Lake boating and Mall Road evening lights",
      "Bhimtal & Naukuchiatal water adventure",
      "Cool mountain climate and scenic colonial architecture",
    ],
    description: "The twin queen hill stations of the North offering cool pine breeze, colonial heritage, misty valleys, and sparkling lakes.",
    itinerary: [
      { day: 1, title: "Delhi → Mussoorie (280 km)", description: "Drive to the Queen of Hills, check in to hotel, evening stroll along vibrant Mall Road." },
      { day: 2, title: "Mussoorie Local Sightseeing", description: "Visit Kempty Falls, Company Garden, Lal Tibba, and Camel's Back Road." },
      { day: 3, title: "Mussoorie → Nainital (310 km)", description: "Scenic trans-hill journey to Nainital, hotel check-in, lakeside leisure." },
      { day: 4, title: "Nainital Lake Tour & Viewpoints", description: "Visit Bhimtal, Sattal, Naukuchiatal, enjoy cable car ride and boating." },
      { day: 5, title: "Nainital → Delhi Departure", description: "Morning souvenir shopping and drive back to Delhi for onward connections." },
    ],
    inclusions: ["Hotels, breakfast & dinner, private cab with fuel/tolls."],
  },
  {
    id: "pkg_004",
    title: "Jim Corbett Wildlife Safari Express",
    slug: "jim-corbett-safari-3d2n",
    type: "domestic",
    destination: "Uttarakhand",
    duration: "3 Days / 2 Nights",
    daysCount: 3,
    priceFrom: "₹9,800 / person",
    category: ["Wildlife", "Adventure", "Photography"],
    highlights: [
      "Open 4x4 Gypsy jungle safari in Corbett Tiger Zone",
      "Resort stay with swimming pool, bonfire, and games",
      "Garjia Devi Temple on Kosi River",
      "Corbett Waterfall & Museum tour",
    ],
    description: "Short, high-intensity wildlife escape tailored for families and photographers looking to encounter majestic Bengal tigers and Asian elephants.",
    itinerary: [
      { day: 1, title: "Delhi → Jim Corbett", description: "Morning drive from Delhi, check in to resort, lunch, evening poolside leisure & bonfire." },
      { day: 2, title: "Open Gypsy Jungle Safari", description: "Early dawn safari in Bijrani/Jhirna/Dhela zone. Evening visit to Garjia temple." },
      { day: 3, title: "Corbett Waterfall → Delhi Return", description: "Breakfast, visit Corbett Museum & waterfall, comfortable drive back to Delhi." },
    ],
    inclusions: ["Jungle resort stay, all buffet meals, 1 open gypsy safari."],
  },
  {
    id: "pkg_005",
    title: "Mukteshwar & Kumaon Hills Tour",
    slug: "mukteshwar-kumaon-hills-tour-4d3n",
    type: "domestic",
    destination: "Uttarakhand",
    duration: "4 Days / 3 Nights",
    daysCount: 4,
    priceFrom: "₹12,400 / person",
    category: ["Hill Station", "Spiritual", "Nature"],
    highlights: [
      "Ancient 350-year-old Mukteshwar Mahadev Temple",
      "Chauli Ki Jali dramatic cliff with valley vistas",
      "Panoramic Himalayan snow-peak views of Nanda Devi & Trishul",
      "Fruit orchards of Ramgarh & pristine pine forests",
      "Offbeat peaceful mountain relaxation",
    ],
    description: "Discover the spiritual serenity of Mukteshwar Dham and the tranquil fruit orchards of the Kumaon Himalayas with breath-taking Himalayan panoramas.",
    itinerary: [
      { day: 1, title: "Delhi → Mukteshwar (340 km)", description: "Scenic mountain drive via Kathgodam and Bhimtal. Check in to scenic resort, evening sunset point walk." },
      { day: 2, title: "Mukteshwar Dham & Chauli Ki Jali", description: "Visit Mukteshwar Mahadev Temple, explore the sacred cleft at Chauli Ki Jali, enjoy rock climbing and valley view." },
      { day: 3, title: "Ramgarh Fruit Orchards & Nature Walk", description: "Visit Ramgarh ('Fruit Bowl of Kumaon'), visit Tagore Top, evening bonfire and stargazing." },
      { day: 4, title: "Mukteshwar → Delhi Departure", description: "Breakfast with mountain views, drive back to Delhi for evening arrival." },
    ],
    inclusions: ["Mountain resort stay, daily breakfast & dinner, private dedicated vehicle, toll/parking."],
  },
  {
    id: "pkg_006",
    title: "Golden Triangle Tour (Delhi Agra Jaipur)",
    slug: "golden-triangle-delhi-agra-jaipur-5d4n",
    type: "domestic",
    destination: "Delhi / Agra / Jaipur",
    duration: "5 Days / 4 Nights",
    daysCount: 5,
    priceFrom: "₹16,500 / person",
    category: ["Heritage", "Cultural", "Popular"],
    highlights: [
      "Taj Mahal & Agra Fort UNESCO World Heritage Sites",
      "Fatehpur Sikri royal abandoned city",
      "Amber Fort elephant / jeep ride in Jaipur",
      "Hawa Mahal, City Palace, and Jantar Mantar",
      "Delhi India Gate, Qutub Minar, and Lotus Temple",
    ],
    description: "India's crowning cultural circuit traversing the historic capital of Delhi, romance of Agra, and royal pink palaces of Jaipur.",
    itinerary: [
      { day: 1, title: "Delhi Sightseeing", description: "Qutub Minar, India Gate, Parliament House, Lotus Temple. Overnight in Delhi." },
      { day: 2, title: "Delhi → Agra (Taj Mahal)", description: "Express drive via Yamuna Expressway. Tour the magnificent Taj Mahal & Agra Fort." },
      { day: 3, title: "Agra → Fatehpur Sikri → Jaipur", description: "En route visit to Fatehpur Sikri, arrive in the Pink City of Jaipur." },
      { day: 4, title: "Jaipur Royal Palace Tour", description: "Amer Fort, Jal Mahal, City Palace, Jantar Mantar, and vibrant Johari Bazaar." },
      { day: 5, title: "Jaipur → Delhi Departure", description: "Morning breakfast, Hawa Mahal photo stop, drive to Delhi airport." },
    ],
    inclusions: ["Heritage hotels, daily breakfast, private AC sedan/SUV, toll & parking."],
  },
  {
    id: "pkg_007",
    title: "Haridwar & Rishikesh Spiritual & Adventure Tour",
    slug: "haridwar-rishikesh-spiritual-adventure-3d2n",
    type: "domestic",
    destination: "Uttarakhand",
    duration: "3 Days / 2 Nights",
    daysCount: 3,
    priceFrom: "₹8,500 / person",
    category: ["Pilgrimage", "Adventure", "Yoga"],
    highlights: [
      "Ganga Aarti ceremony at Har Ki Pauri Haridwar",
      "White-water river rafting from Shivpuri (16 km)",
      "Laxman Jhula, Ram Jhula, and Beatles Ashram in Rishikesh",
      "Cliff jumping, body surfing, and riverbank camping",
      "Mansa Devi & Chandi Devi temple ropeway rides",
    ],
    description: "The ideal weekend blend of sacred Ganga energy, evening Aarti devotion, and adrenaline-pumping white water rafting in Rishikesh.",
    itinerary: [
      { day: 1, title: "Delhi → Haridwar (220 km)", description: "Morning drive, check in, visit Mansa Devi Temple, witness mesmerizing Har Ki Pauri Ganga Aarti. Overnight Haridwar." },
      { day: 2, title: "Haridwar → Rishikesh Adventure", description: "Transfer to Rishikesh, 16 km white water rafting, cliff jump, visit Ram Jhula & Parmarth Niketan Aarti." },
      { day: 3, title: "Rishikesh Sightseeing → Delhi Return", description: "Visit Beatles Ashram and Neelkanth Mahadev temple (optional), return drive to Delhi." },
    ],
    inclusions: ["2 nights hotel/camp accommodation, breakfast & dinner, private cab, 16km rafting session."],
  },
  {
    id: "intl_001",
    title: "Phuket Pattaya Bangkok Island & City Combo",
    slug: "phuket-pattaya-bangkok-7d6n",
    type: "international",
    destination: "Thailand",
    duration: "7 Days / 6 Nights",
    daysCount: 7,
    priceFrom: "₹30,000 / person",
    category: ["Beach", "Island", "Nightlife", "Budget"],
    highlights: [
      "4-star beach resorts in Phuket & Pattaya",
      "Speedboat tour to Coral Island with water sports",
      "Phi Phi Island tour with lunch in Phuket",
      "Bangkok city & temple tour (Golden Buddha & Marble Temple)",
      "Chao Phraya dinner cruise option",
      "Private airport and intercity transfers",
    ],
    description: "Shanvi Hospitality's best-selling international package! Experience Thailand's tropical beaches, exhilarating island watersports, and dynamic Bangkok cityscape.",
    itinerary: [
      { day: 1, title: "Phuket Arrival → Hotel Transfer", description: "Landing in Phuket, private transfer to resort, rest, evening Patong beach exploration." },
      { day: 2, title: "Phi Phi Island Tour by Speedboat", description: "Full day Maya Bay, Viking Cave, snorkeling, and beachfront buffet lunch." },
      { day: 3, title: "Phuket Flight → Bangkok → Pattaya", description: "Domestic flight to Bangkok, private express transfer to Pattaya beach resort." },
      { day: 4, title: "Coral Island (Koh Larn) Speedboat Tour", description: "Parasailing, banana boat, jet skiing at Coral Island, Indian lunch included." },
      { day: 5, title: "Pattaya → Bangkok City Tour", description: "Drive to Bangkok, visit Wat Traimit and Wat Benchamabophit, shopping at MBK / Iconsiam." },
      { day: 6, title: "Bangkok Leisure & Safari World", description: "Optional Safari World and Marine Park or luxury shopping at central Bangkok." },
      { day: 7, title: "Bangkok Departure", description: "Hotel check-out, souvenir shopping, private transfer to Suvarnabhumi Airport." },
    ],
    inclusions: [
      "6 nights accommodation with breakfast in 4-star hotels",
      "Phi Phi Island tour with National Park fees and lunch",
      "Coral Island tour by speedboat with lunch",
      "All airport and intercity transfers by private AC vehicle",
    ],
    exclusions: ["International flights, Thailand visa fees, travel insurance."],
  },
  {
    id: "intl_002",
    title: "Phuket Phi Phi Island Krabi Family Tour",
    slug: "phuket-phi-phi-krabi-8d7n",
    type: "international",
    destination: "Thailand",
    duration: "8 Days / 7 Nights",
    daysCount: 8,
    priceFrom: "₹25,000 / person",
    category: ["Family", "Island", "Beach", "Budget"],
    highlights: [
      "3 Nights Phuket + 2 Nights Phi Phi Island + 2 Nights Krabi",
      "James Bond Island exploration by longtail boat",
      "Krabi Four Islands tour by speedboat",
      "Inter-island ferry tickets included",
      "Tailor-made family-friendly resorts",
    ],
    description: "An unforgettable island-hopping paradise designed for families, featuring turquoise bays, limestone karsts, and tranquil tropical sunsets.",
    inclusions: ["7 nights hotel stay, daily breakfast, ferries, airport transfers, island day trips."],
  },
  {
    id: "intl_003",
    title: "Vietnam Discovery (Hanoi, Halong Bay & Da Nang)",
    slug: "vietnam-discovery-7d6n",
    type: "international",
    destination: "Vietnam",
    duration: "7 Days / 6 Nights",
    daysCount: 7,
    priceFrom: "₹36,000 / person",
    category: ["Cultural", "Adventure", "Heritage", "Nature"],
    highlights: [
      "Overnight luxury cruise on UNESCO World Heritage Halong Bay",
      "Golden Bridge (Giant Hands) at Ba Na Hills, Da Nang",
      "Ancient lantern town of Hoi An",
      "Hanoi Old Quarter French colonial walking tour",
    ],
    description: "Immerse in Vietnam's emerald waters, iconic limestone islands, ancient lantern-lit riverfronts, and extraordinary cuisine.",
    itinerary: [
      { day: 1, title: "Hanoi Arrival & Old Quarter Tour", description: "Arrive in Hanoi, visit Hoan Kiem Lake, Ngoc Son Temple, cyclo ride through the 36 ancient streets." },
      { day: 2, title: "Hanoi → Halong Bay Luxury Cruise", description: "Transfer to Tuan Chau marina, board overnight cruise, kayak around limestone karsts, sunset party on sundeck." },
      { day: 3, title: "Halong Bay → Flight to Da Nang", description: "Tai Chi on sundeck, explore Sung Sot (Surprise) Cave, disembark and flight to coastal Da Nang." },
      { day: 4, title: "Ba Na Hills & Golden Bridge", description: "World's longest cable car to Ba Na Hills, walk on the world-famous Golden Bridge held by giant stone hands." },
      { day: 5, title: "Da Nang → Hoi An Ancient Town", description: "Drive to UNESCO heritage Hoi An, lantern making workshop, Japanese Covered Bridge, night lantern boat ride." },
      { day: 6, title: "My Son Sanctuary & Da Nang Beach", description: "Morning visit to ancient Cham ruins of My Son, afternoon relaxation at My Khe beach." },
      { day: 7, title: "Da Nang Departure", description: "Breakfast, visit Han Market for local coffee and souvenirs, transfer to Da Nang International Airport." },
    ],
    inclusions: ["4-star boutique hotels, overnight Halong Bay cruise with all meals, cable car tickets, domestic flight."],
  },
  {
    id: "intl_003_danang",
    title: "Da Nang & Hoi An Weekend Escape",
    slug: "da-nang-hoi-an-weekend-3d2n",
    type: "international",
    destination: "Vietnam",
    duration: "3 Days / 2 Nights",
    daysCount: 3,
    priceFrom: "₹18,500 / person",
    category: ["Beach", "Heritage", "Short Break"],
    highlights: [
      "Golden Hands Bridge at Ba Na Hills",
      "Hoi An Ancient Lantern Town night stroll",
      "Marble Mountains & caves exploration",
      "My Khe white sand beach relaxation",
    ],
    description: "A compact, high-value coastal Vietnamese getaway covering the iconic Golden Bridge and glowing lantern streets of Hoi An.",
    inclusions: ["2 nights in 4-star Da Nang beachfront resort, breakfast, Ba Na Hills cable car, airport transfers."],
  },
  {
    id: "intl_004",
    title: "Nepal Cultural & Himalayan Odyssey",
    slug: "nepal-kathmandu-pokhara-5d4n",
    type: "international",
    destination: "Nepal",
    duration: "5 Days / 4 Nights",
    daysCount: 5,
    priceFrom: "₹17,000 / person",
    category: ["Spiritual", "Himalayan", "Heritage"],
    highlights: [
      "Pashupatinath Temple & Boudhanath Stupa in Kathmandu",
      "Sarangkot sunrise view over Annapurna mountain range in Pokhara",
      "Phewa Lake boat ride with mountain reflection",
      "No visa needed for Indian citizens",
    ],
    description: "Close-to-home Himalayan splendor blending ancient Buddhist stupas, sacred Hindu shrines, and serene lake vistas.",
    itinerary: [
      { day: 1, title: "Arrival Kathmandu", description: "Arrive at Tribhuvan International Airport, hotel transfer, evening darshan at sacred Pashupatinath Temple." },
      { day: 2, title: "Kathmandu Valley Sightseeing", description: "Visit Boudhanath Stupa, Swayambhunath (Monkey Temple), and historic Kathmandu Durbar Square." },
      { day: 3, title: "Kathmandu → Pokhara (200 km)", description: "Scenic drive along Trishuli river valley to Pokhara, evening boat ride on tranquil Phewa Lake." },
      { day: 4, title: "Sarangkot Sunrise & Pokhara Tour", description: "Early dawn Sarangkot panoramic sunrise over Annapurna & Dhaulagiri, visit Davis Falls & Gupteshwor Cave." },
      { day: 5, title: "Pokhara → Kathmandu Airport Departure", description: "Scenic return drive/flight to Kathmandu for your return flight home." },
    ],
    inclusions: ["3-star/4-star hotel stays, daily breakfast, private vehicle for all transfers and sightseeing, entry permits."],
  },
  {
    id: "intl_005_chitwan",
    title: "Nepal Complete Expedition (Kathmandu, Pokhara & Chitwan Safari)",
    slug: "nepal-kathmandu-pokhara-chitwan-6d5n",
    type: "international",
    destination: "Nepal",
    duration: "6 Days / 5 Nights",
    daysCount: 6,
    priceFrom: "₹24,500 / person",
    category: ["Wildlife", "Himalayan", "Spiritual"],
    highlights: [
      "Chitwan National Park one-horned rhino jeep safari",
      "Pashupatinath Temple sacred evening Aarti",
      "Phewa Lake boat ride with Annapurna snow views",
      "Tharu cultural dance show & jungle canoe ride",
    ],
    description: "The complete Nepal experience spanning heritage temples, mountain sunrise panoramas, and deep jungle wildlife safaris in Chitwan.",
    inclusions: ["5 nights accommodation, all meals in Chitwan safari lodge, jungle activities, private transport."],
  },
];
